# Generated by Django 2.0.6 on 2019-03-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrtymodel',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='relateditemmodel',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
