# Generated by Django 2.0.6 on 2019-03-13 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0002_auto_20190313_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrtymodel',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='enrtymodel',
            name='image',
            field=models.ImageField(upload_to='wiki_app/static/images'),
        ),
        migrations.AlterField(
            model_name='enrtymodel',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
