# Generated by Django 2.0.6 on 2019-03-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0006_auto_20190313_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrtymodel',
            name='image',
            field=models.ImageField(default='/home/student/CodeSchool/IdeaProjects/Django/project3/project2-django-autumn-ragland/wiki_project/wiki_app/static/wiki_app/default.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='relateditemmodel',
            name='image',
            field=models.ImageField(default='/home/student/CodeSchool/IdeaProjects/Django/project3/project2-django-autumn-ragland/wiki_project/wiki_app/static/wiki_app/default.jpeg', upload_to='images'),
        ),
    ]
