# Generated by Django 2.0.6 on 2019-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0010_auto_20190313_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrtymodel',
            name='image',
            field=models.ImageField(blank=True, default='wiki_app/static/wiki_app/default.jpeg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='relateditemmodel',
            name='image',
            field=models.ImageField(blank=True, default='wiki_app/static/wiki_app/default.jpeg', null=True, upload_to='images'),
        ),
    ]
