# Generated by Django 2.0.6 on 2019-03-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0012_auto_20190313_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrtymodel',
            name='create_date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='enrtymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='enrtymodel',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relateditemmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
