# Generated by Django 2.0.6 on 2019-03-13 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0016_auto_20190313_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrtymodel',
            name='create_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrtymodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 20, 57, 20, 105291, tzinfo=utc), null=True),
        ),
    ]
