# Generated by Django 2.0.6 on 2019-03-13 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0019_auto_20190313_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrtymodel',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
