# Generated by Django 2.0.6 on 2019-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0021_auto_20190313_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='relateditemmodel',
            name='create_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='relateditemmodel',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
