# Generated by Django 2.0.6 on 2019-03-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0022_auto_20190314_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrtymodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrtymodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='relateditemmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='relateditemmodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
